### PR TITLE
Moved old files to backup directory #222

### PR DESCRIPTION
**Pull request by TristanPeers**

### CODE REVIEW

**Comment by mikesmithmsm** [comment]
Are you sure you want to do this?  It means we won't be able to easily pull or push changes to the parent?

**Comment by TristanPeers** [comment]
@mikesmithmsm - I need a repo called puppet-kafka to fork official repo from:

https://forge.puppetlabs.com/puppet/kafka

Are you using this repo?

**Comment by mikesmithmsm** [comment]
no mate, not using the repo - but with moving files etc, it means we wouldn't be able to contribute back to that repo, or easily pull updates from it.

**Comment by TristanPeers** [comment]
@mikesmithmsm - thanks for input, after deliberation we will create another repo in travel to be on safe side. Therefore closing this PR.

**Comment by mikesmithmsm** [comment]
:+1:

**Pull request closed without merging**
